name: 'Webform Demo: Application/Evaluation System'
type: module
description: 'Demonstrates how to use the Webform module to build an application/evaluation system.'
package: 'Webform Demo'
core_version_requirement: ^8.7.7 || ^9
dependencies:
  - 'drupal:block'
  - 'drupal:views'
  - 'webform:webform'
  - 'webform:webform_node'

# Information added by Drupal.org packaging script on 2020-05-05
version: '8.x-5.11'
project: 'webform'
datestamp: 1588690393
