name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2020-05-16
version: '9.0.0-beta3'
project: 'drupal'
datestamp: 1589587978
